In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [24]:
# Data import and split
data = pd.read_csv("Naive-Bayes-Classification-Data.csv")
print(data)
X = data.drop('diabetes', axis=1)
y = data['diabetes']
# print(X)
# print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)

     glucose  bloodpressure  diabetes
0         40             85         0
1         40             92         0
2         45             63         1
3         45             80         0
4         40             73         1
..       ...            ...       ...
990       45             87         0
991       40             83         0
992       40             83         0
993       40             60         1
994       45             82         0

[995 rows x 3 columns]

In [25]:
def evaluate_model(model_name, y_test, y_pred, y_prob=None):
    return {
        "Model": model_name,
        "Accuracy": metrics.accuracy_score(y_test, y_pred),
        "Precision": metrics.precision_score(y_test, y_pred),
        "Recall": metrics.recall_score(y_test, y_pred),
        "F1-Score": metrics.f1_score(y_test, y_pred),
        "AUC": metrics.roc_auc_score(y_test, y_prob) if y_prob is not None else np.nan
    }

results = []

In [26]:
# Naive Bayes with Laplacian correction

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)
y_prob = gnb.predict_proba(X_test)[:, 1]

results.append(
    evaluate_model("Naive Bayes", y_test, y_pred, y_prob)
)
print(results[-1])

{'Model': 'Naive Bayes', 'Accuracy': 0.9531772575250836, 'Precision': 0.9507042253521126, 'Recall': 0.9507042253521126, 'F1-Score': 0.9507042253521126, 'AUC': 0.9878666905893962}

In [27]:
# Linear Regression with Stochastic Gradient Descent

from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier(loss="log_loss", penalty="l2", max_iter=1000, eta0=0.01, random_state=45)

sgd.fit(X_train, y_train)


y_pred = sgd.predict(X_test)
y_prob = sgd.predict_proba(X_test)[:, 1]

results.append(
    evaluate_model("SGD (Linear Regression)", y_test, y_pred, y_prob)
)
print(results[-1])

{'Model': 'SGD (Linear Regression)', 'Accuracy': 0.7591973244147158, 'Precision': 0.9861111111111112, 'Recall': 0.5, 'F1-Score': 0.6635514018691588, 'AUC': 0.8493316587422626}

In [28]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)
y_prob = log_reg.predict_proba(X_test)[:, 1]

results.append(
    evaluate_model("Logistic Regression", y_test, y_pred, y_prob)
)
print(results[-1])

{'Model': 'Logistic Regression', 'Accuracy': 0.9498327759197325, 'Precision': 0.9635036496350365, 'Recall': 0.9295774647887324, 'F1-Score': 0.946236559139785, 'AUC': 0.9846371220956311}

In [29]:
from sklearn.tree import DecisionTreeClassifier

dt_entropy = DecisionTreeClassifier(criterion="entropy", random_state=42)
dt_entropy.fit(X_train, y_train)

y_pred = dt_entropy.predict(X_test)
y_prob = dt_entropy.predict_proba(X_test)[:, 1]

results.append(
    evaluate_model("Decision Tree (Entropy)", y_test, y_pred, y_prob)
)
print(results[-1])

{'Model': 'Decision Tree (Entropy)', 'Accuracy': 0.9331103678929766, 'Precision': 0.9121621621621622, 'Recall': 0.9507042253521126, 'F1-Score': 0.9310344827586207, 'AUC': 0.9647438772763972}

In [30]:
import pandas as pd

# Load dataset
df = pd.read_csv("spam.csv", encoding='latin-1')

# Keep only relevant columns
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Convert text to numerical features
vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X_txt = vectorizer.fit_transform(df['message'])
y_txt = df['label']

# Train-test split
X_train_txt, X_test_txt, y_train_txt, y_test_txt = train_test_split(
    X_txt, y_txt, test_size=0.2, random_state=42
)

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l1


model = Sequential([
    Dense(128, activation='relu',
          input_shape=(X_train.shape[1],),
          kernel_regularizer=l1(0.001)),
    Dropout(0.5),

    Dense(64, activation='tanh'),
    Dropout(0.3),

    Dense(1, activation='sigmoid')  # Binary classification
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │       640,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 648,449 (2.47 MB)

 Trainable params: 648,449 (2.47 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    X_train_txt.toarray(), y_train_txt,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

ValueError: Invalid dtype: object

In [ ]:
from sklearn import metrics
import numpy as np

# Predictions
y_prob_txt = model.predict(X_test_txt.toarray()).ravel()
y_pred_txt = (y_prob_txt > 0.5).astype(int)

# Metrics
accuracy = metrics.accuracy_score(y_test_txt, y_pred_txt)
precision = metrics.precision_score(y_test_txt, y_pred_txt)
recall = metrics.recall_score(y_test_txt, y_pred_txt)
f1 = metrics.f1_score(y_test_txt, y_pred_txt)
auc = metrics.roc_auc_score(y_test_txt, y_prob_txt)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("AUC:", auc)

print("\nClassification Report:\n",
      metrics.classification_report(y_test_txt, y_pred_txt))

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

TypeError: Labels in y_true and y_pred should be of the same type. Got y_true=['ham' 'spam'] and y_pred=[0 1]. Make sure that the predictions provided by the classifier coincides with the true labels.

In [ ]:
import matplotlib.pyplot as plt

fpr, tpr, _ = metrics.roc_curve(y_test_txt, y_prob_txt)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {auc:.2f}")
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – Spam Classification (Neural Network)")
plt.legend()
plt.show()

ValueError: y_true takes value in {'ham', 'spam'} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In [ ]:
from tensorflow.keras.datasets import mnist

(X_train_img, y_train_img), (X_test_img, y_test_img) = mnist.load_data()

X_train_img = X_train_img.reshape(-1, 28*28) / 255.0
X_test_img = X_test_img.reshape(-1, 28*28) / 255.0

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 6s 0us/step

In [ ]:
model_img = Sequential([
    Dense(128, activation='relu', input_shape=(784,),
          kernel_regularizer=l1(0.001)),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(10, activation='softmax')
])

model_img.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_img.summary()

model_img.fit(
    X_train_img, y_train_img,
    epochs=10,
    batch_size=64,
    validation_split=0.2
)

/home/mtech/Documents/206125030/DS_AI/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,386 (427.29 KB)

 Trainable params: 109,386 (427.29 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8106 - loss: 1.4145 - val_accuracy: 0.9187 - val_loss: 0.6890
Epoch 2/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8823 - loss: 0.7870 - val_accuracy: 0.9358 - val_loss: 0.5922
Epoch 3/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8935 - loss: 0.7325 - val_accuracy: 0.9430 - val_loss: 0.5775
Epoch 4/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9007 - loss: 0.7018 - val_accuracy: 0.9505 - val_loss: 0.5414
Epoch 5/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9062 - loss: 0.6797 - val_accuracy: 0.9527 - val_loss: 0.5227
Epoch 6/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9078 - loss: 0.6663 - val_accuracy: 0.9533 - val_loss: 0.5238
Epoch 7/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9137 - loss: 0.6468 - val_accuracy: 0.9548 - val_loss: 0.5141
Epoch 8/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9135 - loss: 0.6480 - val_accuracy: 0.9495 - val_loss: 0.5179
Epoch 9/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9155 - loss: 0.6336 - val_accuracy: 0.9545 - val_loss: 0.5154
Epoch 10/10
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9172 - loss: 0.6347 - val_accuracy: 0.9538 - val_loss: 0.5096